ControlFocus("Open", "", "Edit1")
Sleep(5000)
ControlSetText("Open", "", "Edit1", "C:\Users\pp\source\repos\task2\marsframework-master\MarsFramework\su.jpg")
ControlClick("Open", "", "Button1")
Sleep(5000)
